# Generated by Django 6.0.3 on 2026-03-06 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('role_assigned', 'Role Assigned'), ('role_removed', 'Role Removed'), ('material_verified', 'Material Verified'), ('material_rejected', 'Material Rejected'), ('material_request_approved', 'Material Request Approved'), ('material_request_rejected', 'Material Request Rejected'), ('academic_request_approved', 'Academic Request Approved'), ('academic_request_rejected', 'Academic Request Rejected'), ('report_filed', 'Report Filed'), ('report_resolved', 'Report Resolved'), ('ban_issued', 'Ban Issued'), ('ban_lifted', 'Ban Lifted'), ('new_material_in_subject', 'New Material in Subject'), ('mention', 'Mention'), ('system_announcement', 'System Announcement')], max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('icon', models.CharField(default='bell', max_length=50)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('role_assigned', 'Role Assigned'), ('role_removed', 'Role Removed'), ('material_verified', 'Material Verified'), ('material_rejected', 'Material Rejected'), ('material_request_approved', 'Material Request Approved'), ('material_request_rejected', 'Material Request Rejected'), ('academic_request_approved', 'Academic Request Approved'), ('academic_request_rejected', 'Academic Request Rejected'), ('report_filed', 'Report Filed'), ('report_resolved', 'Report Resolved'), ('ban_issued', 'Ban Issued'), ('ban_lifted', 'Ban Lifted'), ('new_material_in_subject', 'New Material in Subject'), ('mention', 'Mention'), ('system_announcement', 'System Announcement')], max_length=60)),
                ('email_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['notification_type'],
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
