# Generated by Django 5.0.14 on 2026-02-17 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('misinformation', 'Misinformation'), ('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('copyright', 'Copyright Violation'), ('academic_integrity', 'Academic Integrity Violation'), ('other', 'Other')], help_text='Reason for the report', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('object_id', models.UUIDField(blank=True, help_text='ID of the content being reported', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], default='pending', help_text='Current status of the report', max_length=20)),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Evidence supporting the report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of content being reported', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(help_text='User who submitted the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ban_type', models.CharField(choices=[('temporary', 'Temporary Ban'), ('permanent', 'Permanent Ban'), ('content_restriction', 'Content Restriction'), ('feature_restriction', 'Feature Restriction')], help_text='Type of ban', max_length=50)),
                ('reason', models.TextField(help_text='Reason for the ban')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('lifted', 'Lifted'), ('pending', 'Pending')], default='pending', help_text='Current status of the ban', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('starts_at', models.DateTimeField(blank=True, help_text='When the ban takes effect', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the ban expires (null for permanent)', null=True)),
                ('scope', models.JSONField(blank=True, default=dict, help_text='Scope of the ban (e.g., which features are restricted)')),
                ('banned_by', models.ForeignKey(help_text='Moderator who issued the ban', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_issued', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Banned user', on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL)),
                ('related_report', models.ForeignKey(blank=True, help_text='Report that led to this ban', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_bans', to='moderation.report')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Reason for the appeal')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Evidence supporting the appeal')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the appeal', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Moderator who reviewed the appeal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User appealing', on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL)),
                ('ban', models.ForeignKey(blank=True, help_text='Ban being appealed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='moderation.ban')),
                ('report', models.ForeignKey(blank=True, help_text='Report being appealed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='moderation.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='moderation__status_3fc7e7_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reason'], name='moderation__reason_460c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter'], name='moderation__reporte_6f6e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='ban',
            index=models.Index(fields=['user'], name='moderation__user_id_ca5afc_idx'),
        ),
        migrations.AddIndex(
            model_name='ban',
            index=models.Index(fields=['status'], name='moderation__status_6604ce_idx'),
        ),
        migrations.AddIndex(
            model_name='ban',
            index=models.Index(fields=['-expires_at'], name='moderation__expires_6857a5_idx'),
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['user'], name='moderation__user_id_483e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['status'], name='moderation__status_abb5dc_idx'),
        ),
    ]
