# Generated by Django 5.0.14 on 2026-02-17 09:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FederatedInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this instance', primary_key=True, serialize=False)),
                ('instance_name', models.CharField(help_text='Name of the federated instance', max_length=255, unique=True)),
                ('domain', models.CharField(help_text='Domain name of the instance', max_length=255, unique=True)),
                ('api_url', models.URLField(help_text='Base URL for the instance API')),
                ('description', models.TextField(blank=True, help_text='Description of the instance')),
                ('public_key', models.TextField(help_text='Public key for verifying signatures')),
                ('api_key', models.CharField(help_text='API key for authenticating requests', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending Verification')], default='pending', help_text='Current status of the instance', max_length=20)),
                ('is_trusted', models.BooleanField(default=False, help_text='Whether this instance is trusted')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last time this instance was contacted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain'], name='federation__domain_a80364_idx'), models.Index(fields=['status'], name='federation__status_aa2a7f_idx')],
            },
        ),
        migrations.CreateModel(
            name='FederationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('sync_request', 'Synchronization Request'), ('sync_response', 'Synchronization Response'), ('query', 'Query'), ('notification', 'Notification'), ('error', 'Error')], help_text='Type of message', max_length=50)),
                ('subject', models.CharField(help_text='Message subject', max_length=255)),
                ('payload', models.JSONField(help_text='Message payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', help_text='Current status of the message', max_length=20)),
                ('signature', models.TextField(blank=True, help_text='Digital signature for verification')),
                ('error_message', models.TextField(blank=True, help_text='Error details if delivery failed')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of delivery attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('from_instance', models.ForeignKey(help_text='Source instance', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='federation.federatedinstance')),
                ('to_instance', models.ForeignKey(help_text='Destination instance', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='federation.federatedinstance')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_instance'], name='federation__from_in_d1b4b8_idx'), models.Index(fields=['to_instance'], name='federation__to_inst_1df0b8_idx'), models.Index(fields=['status'], name='federation__status_0f701a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FederationSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync'), ('bilateral', 'Bilateral Sync')], default='incremental', help_text='Type of synchronization', max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='initiated', help_text='Synchronization status', max_length=20)),
                ('records_synced', models.IntegerField(default=0, help_text='Number of records synchronized')),
                ('errors_count', models.IntegerField(default=0, help_text='Number of errors during synchronization')),
                ('data_synced', models.JSONField(blank=True, default=dict, help_text='Meta-information about synced data')),
                ('error_log', models.JSONField(blank=True, default=list, help_text='Log of errors during sync')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('instance', models.ForeignKey(help_text='Federated instance being synced', on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='federation.federatedinstance')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['instance'], name='federation__instanc_f3c79e_idx'), models.Index(fields=['status'], name='federation__status_328285_idx')],
            },
        ),
    ]
