# Generated by Django 6.0.3 on 2026-03-06 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='e.g. learngrid.university.edu', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='instance-logos/%Y/%m/')),
                ('software_version', models.CharField(blank=True, max_length=50)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('public_key', models.TextField(blank=True, help_text='RSA public key PEM')),
                ('keypair_created_at', models.DateTimeField(blank=True, null=True)),
                ('trust_level', models.CharField(choices=[('trusted', 'Trusted'), ('neutral', 'Neutral'), ('blocked', 'Blocked')], default='neutral', max_length=20)),
                ('is_home', models.BooleanField(default=False)),
                ('registration_open', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('material_count', models.PositiveIntegerField(default=0)),
                ('user_count', models.PositiveIntegerField(default=0)),
                ('last_synced_stats_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_reachable', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='FederatedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(blank=True, max_length=100)),
                ('subject_name', models.CharField(blank=True, max_length=255)),
                ('semester_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255)),
                ('file_url', models.URLField(max_length=2000)),
                ('external_url', models.URLField(blank=True, max_length=2000)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('uploaded_by_username', models.CharField(max_length=150)),
                ('verified_by_username', models.CharField(blank=True, max_length=150)),
                ('verification_status', models.CharField(default='verified', max_length=50)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('original_created_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('source_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='federated_materials', to='federation.instance')),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='FederatedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=255, unique=True)),
                ('activity_type', models.CharField(choices=[('material_shared', 'Material Shared'), ('material_updated', 'Material Updated'), ('material_removed', 'Material Removed'), ('user_reported', 'User Reported'), ('instance_announcement', 'Instance Announcement'), ('instance_stats_update', 'Instance Stats Update')], max_length=50)),
                ('payload', models.JSONField()),
                ('signature', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('from_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_activities', to='federation.instance')),
                ('to_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_activities', to='federation.instance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstanceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('block_type', models.CharField(choices=[('manual', 'Manual'), ('auto_spam_detection', 'Auto (Spam Detection)'), ('reported', 'Reported')], default='manual', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_blocks', to=settings.AUTH_USER_MODEL)),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='federation.instance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['domain'], name='federation__domain_c8da86_idx'),
        ),
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['trust_level'], name='federation__trust_l_c25fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['is_home'], name='federation__is_home_f8c267_idx'),
        ),
        migrations.AddIndex(
            model_name='federatedmaterial',
            index=models.Index(fields=['material_type'], name='federation__materia_78589a_idx'),
        ),
        migrations.AddIndex(
            model_name='federatedmaterial',
            index=models.Index(fields=['verification_status'], name='federation__verific_c942ea_idx'),
        ),
        migrations.AddIndex(
            model_name='federatedmaterial',
            index=models.Index(fields=['source_instance', 'is_removed'], name='federation__source__2d7681_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='federatedmaterial',
            unique_together={('original_id', 'source_instance')},
        ),
        migrations.AddIndex(
            model_name='federatedactivity',
            index=models.Index(fields=['activity_type'], name='federation__activit_fa3615_idx'),
        ),
        migrations.AddIndex(
            model_name='federatedactivity',
            index=models.Index(fields=['status'], name='federation__status_f975b7_idx'),
        ),
        migrations.AddIndex(
            model_name='federatedactivity',
            index=models.Index(fields=['from_instance'], name='federation__from_in_a85633_idx'),
        ),
        migrations.AddIndex(
            model_name='federatedactivity',
            index=models.Index(fields=['created_at'], name='federation__created_86c107_idx'),
        ),
    ]
