# Generated by Django 5.0.14 on 2026-02-17 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the material type', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the material type')),
                ('is_system_type', models.BooleanField(default=False, help_text='Whether this is a system-defined type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the material', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the material')),
                ('file', models.FileField(help_text='Material file', upload_to='course_materials/%Y/%m/%d/')),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('enrolled', 'Enrolled Students Only'), ('restricted', 'Restricted')], default='enrolled', help_text='Who can access this material', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('is_archived', models.BooleanField(default=False, help_text='Whether this material is archived')),
                ('view_count', models.IntegerField(default=0, help_text='Number of times this material has been viewed')),
                ('download_count', models.IntegerField(default=0, help_text='Number of times this material has been downloaded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Associated course', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academic.course')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
                ('material_type', models.ForeignKey(help_text='Type of material', on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='materials.materialtype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course'], name='materials_c_course__2da531_idx'), models.Index(fields=['material_type'], name='materials_c_materia_88c2cc_idx'), models.Index(fields=['-created_at'], name='materials_c_created_bf1fbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Note title', max_length=255)),
                ('content', models.TextField(help_text='Note content')),
                ('is_public', models.BooleanField(default=False, help_text='Whether the note is publicly visible')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Associated course', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academic.course')),
                ('created_by', models.ForeignKey(help_text='User who created the note', on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, help_text='Associated subject', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academic.subject')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['course'], name='materials_n_course__18fcb0_idx'), models.Index(fields=['created_by'], name='materials_n_created_17e1bd_idx'), models.Index(fields=['-updated_at'], name='materials_n_updated_10dcd1_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the question paper', max_length=255)),
                ('paper_type', models.CharField(choices=[('midterm', 'Midterm Exam'), ('final', 'Final Exam'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('practice', 'Practice Paper')], help_text='Type of question paper', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Difficulty level', max_length=20)),
                ('file', models.FileField(help_text='Question paper file', upload_to='question_papers/%Y/%m/%d/')),
                ('solution_file', models.FileField(blank=True, help_text='Solution file', null=True, upload_to='question_papers/solutions/%Y/%m/%d/')),
                ('exam_date', models.DateField(blank=True, help_text='Date when the exam was conducted', null=True)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=1, help_text='Total marks for the paper', max_digits=5, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration of exam in minutes', null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Whether this paper is archived')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Associated course', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='academic.course')),
                ('subject', models.ForeignKey(blank=True, help_text='Associated subject', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='academic.subject')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the paper', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_question_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-exam_date', '-created_at'],
                'indexes': [models.Index(fields=['course'], name='materials_q_course__c2121e_idx'), models.Index(fields=['paper_type'], name='materials_q_paper_t_3c310b_idx'), models.Index(fields=['-exam_date'], name='materials_q_exam_da_e81758_idx')],
            },
        ),
    ]
