# Generated by Django 5.0.14 on 2026-02-17 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the action', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Human-readable label for the action', max_length=255)),
                ('category', models.CharField(choices=[('account', 'Account Management'), ('academic', 'Academic Operations'), ('content', 'Content Management'), ('moderation', 'Moderation'), ('federation', 'Federation'), ('system', 'System')], help_text='Category of the action', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of what this action represents')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Whether this action involves sensitive data')),
                ('requires_reason', models.BooleanField(default=False, help_text='Whether a reason must be provided for this action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='audit_audit_categor_fa1e18_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('execute', 'Execute'), ('export', 'Export')], help_text='Type of operation', max_length=20)),
                ('object_id', models.UUIDField(blank=True, help_text='ID of the object being acted upon', null=True)),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='Previous values of changed fields')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='New values of changed fields')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the request')),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Request data (for sensitive operations)')),
                ('reason', models.TextField(blank=True, help_text='Reason for the action')),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP status code of the operation', null=True)),
                ('result', models.CharField(default='success', help_text='Result of the operation (success/failure)', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Error message if the operation failed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the action')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.ForeignKey(help_text='Action being audited', on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='audit.auditaction')),
                ('actor', models.ForeignKey(help_text='User performing the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of object being acted upon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditViewer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('audit_log', models.ForeignKey(help_text='Audit log being viewed', on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='audit.auditlog')),
                ('viewer', models.ForeignKey(help_text='User viewing the audit logs', on_delete=django.db.models.deletion.CASCADE, related_name='audit_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor'], name='audit_audit_actor_i_17b775_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_audit_action__cf28aa_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_1175ab_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['result'], name='audit_audit_result_4e9791_idx'),
        ),
        migrations.AddIndex(
            model_name='auditviewer',
            index=models.Index(fields=['viewer'], name='audit_audit_viewer__b7675b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auditviewer',
            unique_together={('viewer', 'audit_log')},
        ),
    ]
