# Generated by Django 5.0.14 on 2026-02-17 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Course code (e.g., CS101-001)', max_length=100)),
                ('section', models.CharField(default='001', help_text='Course section number', max_length=50)),
                ('capacity', models.IntegerField(default=30, help_text='Maximum number of students', validators=[django.core.validators.MinValueValidator(1)])),
                ('schedule', models.JSONField(blank=True, default=dict, help_text='Course schedule (days, times, location)')),
                ('syllabus', models.TextField(blank=True, help_text='Course syllabus and learning objectives')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the course is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['semester', 'subject', 'section'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Department code (e.g., CS, MATH)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Full name of the department', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Department description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the department is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Semester code (e.g., Fall2024, Spring2025)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Full name of the semester', max_length=255)),
                ('semester_type', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], help_text='Type of semester', max_length=10)),
                ('year', models.IntegerField(help_text='Academic year', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('start_date', models.DateField(help_text='Semester start date')),
                ('end_date', models.DateField(help_text='Semester end date')),
                ('registration_open', models.DateTimeField(blank=True, help_text='When student registration opens', null=True)),
                ('registration_close', models.DateTimeField(blank=True, help_text='When student registration closes', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Whether this is the current active semester')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-semester_type'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Subject code', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Subject name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Subject description and syllabus')),
                ('credits', models.DecimalField(decimal_places=1, help_text='Number of academic credits', max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('level', models.CharField(blank=True, help_text='Subject level (e.g., 100-level, 200-level)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subject is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['department', 'code'],
            },
        ),
    ]
