# Generated by Django 5.0.14 on 2026-02-17 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='co_instructors',
            field=models.ManyToManyField(blank=True, help_text='Co-instructors for this course', related_name='co_taught_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Instructor teaching this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Head of the department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['code'], name='academic_se_code_dc59c3_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['-year'], name='academic_se_year_aa9c66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('semester_type', 'year')},
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(help_text='Semester when this course is offered', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academic.semester'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(help_text='Department offering this subject', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.department'),
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Prerequisite subjects', related_name='dependent_subjects', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(help_text='Subject this course is based on', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academic.subject'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='academic_de_code_81d7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='academic_de_name_67e679_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='academic_su_code_d89c14_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['department'], name='academic_su_departm_c743ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('department', 'code')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='academic_co_code_9372b3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['semester'], name='academic_co_semeste_242c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor'], name='academic_co_instruc_e545b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('subject', 'semester', 'section')},
        ),
    ]
