# Generated by Django 6.0.3 on 2026-03-06 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_academic_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academic.department'),
        ),
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic.course'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectmapping',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_mappings', to='academic.department'),
        ),
        migrations.AddField(
            model_name='subjectmapping',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mappings', to='academic.semester'),
        ),
        migrations.AddField(
            model_name='subjectmapping',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='academic.subject'),
        ),
        migrations.AddIndex(
            model_name='academicrequest',
            index=models.Index(fields=['status'], name='academic_ac_status_9a50d9_idx'),
        ),
        migrations.AddIndex(
            model_name='academicrequest',
            index=models.Index(fields=['request_type'], name='academic_ac_request_e70065_idx'),
        ),
        migrations.AddIndex(
            model_name='academicrequest',
            index=models.Index(fields=['requester'], name='academic_ac_request_f53ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='academic_de_code_81d7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='academic_de_name_67e679_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='academic_de_is_acti_daf21a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='academic_co_code_9372b3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department'], name='academic_co_departm_294021_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='academic_co_is_acti_02512a_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['course'], name='academic_se_course__6e98c0_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['is_active'], name='academic_se_is_acti_e170ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('number', 'academic_year', 'course')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='academic_su_code_d89c14_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_common'], name='academic_su_is_comm_c4a264_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_active'], name='academic_su_is_acti_4e0783_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectmapping',
            index=models.Index(fields=['subject', 'semester'], name='academic_su_subject_e90513_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectmapping',
            index=models.Index(fields=['department'], name='academic_su_departm_62ee56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectmapping',
            unique_together={('subject', 'semester', 'department')},
        ),
    ]
